### ISSUE TITLE
Outline Alignment Pipeline

### ISSUE THREAD

**Issue by kellrott** [ohsu-cedar-comp-hub/WGS-nextflow-workflow#13]
Define all of the processes needed to implement the alignment pipeline. 

- [x] Document and compare against parameters used by the GDC pipeline https://docs.gdc.cancer.gov/Data/Bioinformatics_Pipelines/DNA_Seq_Variant_Calling_Pipeline/

**Comment by rlancaster96** [comment]
Merged with outline somatic variant calling branch readme
