### ISSUE TITLE
snpEff script differs for conda vs containers

### ISSUE THREAD

**Issue by rlancaster96** [ohsu-cedar-comp-hub/WGS-nextflow-workflow#55]
**Description of problem**
snpEff is a java program. 
When running with conda, it is invoked like this: `snpEff {args}`. 
When running in a container, I have to invoke it with the full file path and filename extension like this: `/path/to/snpEff/snpEff.jar {args}`. 
I want to use only one script in Nextflow for running with either conda and containers, which means I would like to either invoke snpEff with conda by passing it the full file path or invoke snpEff with only `snpEff` for Singularity/Docker.

**setup**
Here is the Dockerfile used to build the container: 

```Dockerfile
FROM openjdk:17-jdk-slim

WORKDIR /usr/src/app

RUN apt-get update && \
    apt-get install -y wget unzip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN wget https://snpeff.blob.core.windows.net/versions/snpEff_latest_core.zip && \
    unzip snpEff_latest_core.zip && \
    rm snpEff_latest_core.zip

# assuming snpeff looks for data in /usr/src/app/snpEff/data (instead maybe we download at runtime and mount as a volume?)
RUN java -jar snpEff/snpEff.jar download -v GRCh38.86

# ENV _JAVA_OPTIONS=-Xmx8g

ENTRYPOINT ["java", "-jar"]
```

**attempts to resolve**

1. Specifying a symlink in the Dockerfile, `RUN ln -s snpEff path/to/snpEff/snpEff.jar`
2. Specifying an alias in the Dockerfile and writing to the .bashrc file in the container `RUN echo "alias foobar='snpEff/snpEff.jar'" >> /root/.bashrc`
3. Changing ENV PATH curly brackets in the Dockerfile `ENV PATH path/to/snpEff:$PATH` and `ENV PATH path/to/snpEff:${PATH}`
4. Moving the executable file to usr/local `RUN mv snpEff /usr/local/ && chmod 755 /usr/local/snpEff/snpEff.jar` 
5. Mounting a entrypoint.sh script to run a symlinking script at launch; this worked if the symlink provided was "foobar" but failed when the symlink was "snpEff" due to snpEff already being a file. 
```
FROM openjdk:17-jdk-slim

WORKDIR /usr/src/app

RUN apt-get update && \
    apt-get install -y wget unzip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN wget https://snpeff.blob.core.windows.net/versions/snpEff_latest_core.zip && \
    unzip snpEff_latest_core.zip && \
    rm snpEff_latest_core.zip

# assuming snpeff looks for data in /usr/src/app/snpEff/data (instead maybe we download at runtime and mount as a volume?)
RUN java -jar snpEff/snpEff.jar download -v GRCh38.86

# set up entrypoint
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT /usr/local/bin/entrypoint.sh && java -jar snpEff
```
the entrypoint script for the symlink:
```
#!/bin/sh

ln -s snpEff/snpEff.jar snpEff
```

6. Building the Dockerfile from micromamba base - this correctly invokes the program with only `snpEff` but unfortunately this behavior was not translated to running in Nextflow with Singularity and resulted in a command not found error. (+ added downside of pulling this image takes a long time).
```Dockerfile
FROM mambaorg/micromamba:1.5.8
# mount yaml file to build environment
COPY --chown=$MAMBA_USER:$MAMBA_USER env.yml /tmp/env.yaml
# build environment
RUN micromamba install -y -n base -f /tmp/env.yaml && \
    micromamba clean --all --yes
# args to run conda environment in dockerfile
ARG MAMBA_DOCKERFILE_ACTIVATE=1
# self update
RUN micromamba update snpeff
# download reference genome
RUN snpEff download -v GRCh38.86
```

**Links to similar issues**
- https://askubuntu.com/questions/868017/how-do-i-make-my-jar-file-execute-like-a-regular-application-from-terminal
- https://stackoverflow.com/questions/27093612/in-a-dockerfile-how-to-update-path-environment-variable

**Comment by jordan2lee** [comment]
One solution could be to add snpeff to your PATH for conda. I assume most users who could invoke via conda would be able to also update their PATH. So that invoking the container for conda or nextflow would only require `snpEff` (neither conda or nextflow invoke with full path)
